Repository recurly/react-recurly, pull requests merged in 2020-04, with the labels that each got.

#54 Fix ref usage
  README.mdx
  demo/src/card-element-demo.js
  demo/src/individual-card-elements-demo.js
  docs/2-hooks/useRecurly.stories.mdx
Labels: documentation

#57 Use checkout pricing currency
  lib/use-checkout-pricing.js
  package-lock.json
  package.json
  test/use-checkout-pricing.test.js
Labels: bug

#60 Adds types
  .npmignore
  .travis.yml
  Makefile
  jest.config.js
  package-lock.json
  package.json
  types/index.d.ts
  types/test-types.tsx
  types/tsconfig.json
  types/tslint.json
Labels: new feature

#59 Rewrites tests for useCheckoutPricing to use test server
  Makefile
  globalSetup.js
  jest.config.js
  jest.setup.js
  lib/use-checkout-pricing.js
  package-lock.json
  package.json
  test/provider.test.js
  test/support/helpers.js
  test/use-checkout-pricing.test.js
Labels: tests & build
