Repository recurly/react-recurly, pull requests merged in 2020-01, with the labels that each got.

#10 Splits Demo from main package, adds tests, adds CI config
  .gitignore
  .npmignore
  .travis.yml
  Makefile
  README.md
  babel.config.js
  demo/.env
  demo/index.js
  demo/package.json
  demo/public/index.html
  demo/src/card-element-demo.js
  demo/src/individual-card-elements-demo.js
  demo/src/three-d-secure-demo.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  test/index.test.js
  test/provider.test.js
  test/support/helpers.js
  test/use-recurly.test.js
  webpack.config.js
Labels: tests & build

#11 Transpiles dist targets prior to publication
  .gitignore
  .npmignore
  Makefile
  babel.config.js
  package-lock.json
  package.json
Labels: tests & build

#12 Bumps demo version
  demo/package.json
Labels: dependency

#13 Fixes demo
  demo/.env
  demo/src/card-element-demo.js
  demo/src/index.js
  demo/src/individual-card-elements-demo.js
  demo/src/three-d-secure-demo.js
Labels: demo only

#8 Pricing multiple subscriptions
  demo/public/index.html
  demo/src/checkout-pricing.js
  demo/src/index.js
  lib/index.js
  lib/use-checkout-pricing.js
Labels: new feature

#15 Adds Storybook
  Makefile
  README.md
  README.mdx
  docs/.storybook/main.js
  docs/.storybook/preview-head.html
  docs/.storybook/preview.js
  docs/0-introduction/getting-started.stories.mdx
  docs/0-introduction/interactive-demo.stories.mdx
  docs/1-components/CardElement.stories.js
  docs/1-components/Elements.stories.mdx
  docs/1-components/RecurlyProvider.stories.mdx
  docs/1-components/ThreeDSecureAction.stories.mdx
  docs/1-components/individual/CardCvvElement.stories.js
  docs/1-components/individual/CardMonthElement.stories.js
  docs/1-components/individual/CardNumberElement.stories.js
  docs/1-components/individual/CardYearElement.stories.js
  docs/2-hooks/useRecurly.stories.mdx
  docs/shared/decorators.js
  docs/shared/knobs.js
  docs/shared/prop-types.js
  lib/element/element.js
  lib/elements.js
  lib/provider.js
  lib/three-d-secure-action.js
  package-lock.json
  package.json
Labels: documentation

#16 Adds <Elements /> tests
  Makefile
  test/elements.test.js
  test/provider.test.js
Labels: tests & build

#20 Adds Coveralls
  .github/workflows/main.yml
  .gitignore
  .npmignore
  .travis.yml
  Makefile
  jest.config.js
Labels: tests & build

#21 Adds GitHub Action to publish documentation
  .github/workflows/docs.yml
  .github/workflows/main.yml
  Makefile
  package-lock.json
  package.json
Labels: tests & build

#23 Adds issue templates
  .github/ISSUE_TEMPLATE/01_bug_report.md
  .github/ISSUE_TEMPLATE/02_question_or_feature_request.md
Labels: documentation

#14 Pricing multiple adjustments
  demo/src/checkout-pricing.js
  lib/use-checkout-pricing.js
Labels: new feature

#22 Completes test suite
  .travis.yml
  Makefile
  README.mdx
  jest.setup.js
  lib/element/element.js
  lib/three-d-secure-action.js
  package-lock.json
  package.json
  test/element/card-cvv.test.js
  test/element/card-month.test.js
  test/element/card-number.test.js
  test/element/card-year.test.js
  test/element/card.test.js
  test/elements.test.js
  test/provider.test.js
  test/support/helpers.js
  test/support/suites.js
  test/three-d-secure-action.test.js
  test/use-recurly.test.js
Labels: enhancement, tests & build
