Repository recurly/react-recurly, pull requests merged in 2023-10, with the labels that each got.

#217 Adds hostname configuration
  lib/provider.jsx
  package-lock.json
  test/provider.test.jsx
Labels: enhancement

#218 Always include items labeled 'new feature' in changelog
  .changelog_config.yaml
Labels: internal

#221 Updating setup-node and reversing README link
  .github/workflows/docs.yml
  README.md
  README.mdx
Labels: documentation

#222 Fixes issue with Storybook deployment
  .github/workflows/docs.yml
  README.mdx
Labels: documentation
